! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Global Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : second_Global.f90
! Time                 : Wed Feb  5 13:33:52 2020
! Working directory    : /Users/roldin/mcm_kpp/chemistry_DMS_20200205
! Equation file        : second.kpp
! Output root filename : second
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE second_Global

  USE second_Parameters, ONLY: dp, NSPEC, NVAR, NFIX, NREACT
  PUBLIC
  SAVE


! Declaration of global variables

! C - Concentration of all species
  REAL(kind=dp) :: C(NSPEC)
! VAR - Concentrations of variable species (global)
  REAL(kind=dp) :: VAR(NVAR)
! FIX - Concentrations of fixed species (global)
  REAL(kind=dp) :: FIX(NFIX)
! VAR, FIX are chunks of array C
      EQUIVALENCE( C(1),VAR(1) )
! RCONST - Rate constants (global)
  REAL(kind=dp) :: RCONST(NREACT)
! TIME - Current integration time
  REAL(kind=dp) :: TIME
! SUN - Sunlight intensity between [0,1]
  REAL(kind=dp) :: SUN
! TEMP - Temperature
  REAL(kind=dp) :: TEMP
! RTOLS - (scalar) Relative tolerance
  REAL(kind=dp) :: RTOLS
! TSTART - Integration start time
  REAL(kind=dp) :: TSTART
! TEND - Integration end time
  REAL(kind=dp) :: TEND
! DT - Integration step
  REAL(kind=dp) :: DT
! ATOL - Absolute tolerance
  REAL(kind=dp) :: ATOL(NVAR)
! RTOL - Relative tolerance
  REAL(kind=dp) :: RTOL(NVAR)
! STEPMIN - Lower bound for integration step
  REAL(kind=dp) :: STEPMIN
! STEPMAX - Upper bound for integration step
  REAL(kind=dp) :: STEPMAX
! CFACTOR - Conversion factor for concentration units
  REAL(kind=dp) :: CFACTOR

! INLINED global variable declarations

 REAL(dp)::M, N2, O2, RO2, H2O
 
! INLINED global variable declarations

! variables
  INTEGER, PARAMETER :: NPHOT = 101
  INTEGER, PARAMETER :: NKVALUES = 63

  REAL(kind=dp) :: RH,PRESS,RES1,RES2
  REAL(kind=dp) :: J(NPHOT)
  REAL(kind=dp) :: KMT01,KMT02,KMT03,KMT04,KMT05,KMT06,KMT07,KMT08,KMT09,KMT10
  REAL(kind=dp) :: KMT11,KMT12,KMT13,KMT14,KMT15,KMT16,KMT17,KMT18
  REAL(kind=dp) :: KFPAN,KBPAN,KRO2NO,KRO2HO2,KAPHO2,KAPNO,KRO2NO3,KNO3AL
  REAL(kind=dp) :: KDEC,KROPRIM,KROSEC,KCH3O2,K298CH3O2,K_CI,K_h2so4
  REAL(kind=dp) :: KMT34,KMT35,KMT36,KMT37,KMT38,KMT39,KMT40,KMT41,KMT42
  REAL(kind=dp) :: KMT46,KMT47,KMT48,KMT49,KMT50,KMT51,KMT52,KMT53
  REAL(kind=dp) :: KMT54,KMT55,KMT56,KMT57,KMT58,KMT59,KMT60,KMT61
  REAL(kind=dp) :: KMT62,KMT63
  REAL(kind=dp) :: kCl2_g_aq, kCl2_aq_g, kCl_g_aq, kCl_aq_g, kClO_g_aq, kClO_aq_g, kClO2_g_aq, & 
kClO2_aq_g, kHCl_g_aq, kHCl_aq_g, kHOCl_g_aq, kHOCl_aq_g, kClNO_g_aq, kClNO_aq_g, &
kClNO2_g_aq, kClNO2_aq_g, kClNO3_g_aq, kClNO3_aq_g, kBr2_g_aq, kBr2_aq_g, kBr_g_aq, & 
kBr_aq_g, kBrO_g_aq, kBrO_aq_g, kHBr_g_aq, kHBr_aq_g, kHOBr_g_aq, kHOBr_aq_g, kBrNO2_g_aq, &
kBrNO2_aq_g, kBrNO3_g_aq, kBrNO3_aq_g, kBrCl_g_aq, kBrCl_aq_g, kI2_g_aq, kI2_aq_g, kI_g_aq, &
kI_aq_g, kIO_g_aq, kIO_aq_g, kOIO_g_aq, kOIO_aq_g, kI2O2_g_aq, kI2O2_aq_g, kHI_g_aq, &
kHI_aq_g, kHOI_g_aq, kHOI_aq_g, kHIO3_g_aq, kHIO3_aq_g, kINO2_g_aq, kINO2_aq_g, kINO3_g_aq, &
kINO3_aq_g, kICl_g_aq, kICl_aq_g, kIBr_g_aq, kIBr_aq_g, kO3_g_aq, kO3_aq_g, kOH_g_aq, &
kOH_aq_g, kH2O2_g_aq, kH2O2_aq_g, kDMS_g_aq, kDMS_aq_g, kDMSO_g_aq, kDMSO_aq_g, &
kDMSO2_g_aq, kDMSO2_aq_g, kMSIA_g_aq, kMSIA_aq_g, kHPMTF_g_aq, kHPMTF_aq_g, kSO2_g_aq, &
kSO2_aq_g, kHO2_g_aq, kHO2_aq_g, kNO3_g_aq, kNO3_aq_g, kRO2_g_aq, kRO2_aq_g, kHCHO_g_aq, &
kHCHO_aq_g, kNO2_g_aq, kNO2_aq_g, kO2_g_aq, kO2_aq_g, kSO3_g_aq, kSO3_aq_g, &
kNH3_g_aq, kNH3_aq_g, kHOOCH2SCO_g_aq, kHOOCH2SCO_aq_g, kH2SO4_g_aq, kH2SO4_aq_g,&
kMSA_g_aq, kMSA_aq_g, kHNO3_g_aq, kHNO3_aq_g, cw, Na, H_ion, OH_ion
   
  
  REAL(kind=dp) :: K16ISOM1,K15ISOM1,K14ISOM1,KBPPN


END MODULE second_Global

